development:
  debug: true
injuries:
  bleed:
    chancePercent: 0.15
    damageInterval: 40
    damagePercent: 0.05
    tickDuration: -1
    soundOnInjure: true
    soundOnDamage: true
    onInjuryMessage: You are now bleeding -- patch yourself up quick or you will die.
    onRemedyMessage: You are no longer bleeding.
  crippled:
    chancePercent: 0.5
    slowPercent: 0.33
    tickDuration: -1
    soundOnInjure: true
    onInjuryMessage: You are now crippled -- get a splint or your movement will be
      slowed.
    onRemedyMessage: You are no longer crippled.
remedies:
  bandage:
    label: Bandage
  splint:
    label: Splint
