name: Injured
version: 1.0.0
main: io.github.charlock.injured.Injured
description: A plugin for PaperMC to enable a mild injury system.
author: Charlotte Lockett <cflockett4@gmail.com>
website: https://github.com/char-lock/injured
api-version: 1.19
commands:
  injure:
    description: Apply an injury to a player.
    usage: Syntax Error! /injure [player] [injury]
  uninjure:
    description: Remove an injury from a player.
    usage: Syntax Error! /uninjure [player] [injury]